version: "3.3"

services:
  web:
    image: sports_board_frontend_new
    container_name: sports_board_frontend_new
    restart: always
    build:
        context: .
    ports:
      - "3019:3000"
    env_file:
    - ".env"
    command: sh -c "cd /app && serve -s build"
    networks:
      - frontend_default

networks:
  frontend_default:
    external: true