version: "3.3"
services:
  app:
    image: sports_board_backend
    container_name: sports_board_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - sports_board_images:/usr/src/app/backend/images
    ports:
      - "2026:3001"
    env_file:
      - ".env"
    networks:
      - backend_sports-board-strapi

volumes:
  sports_board_images:

networks:
  backend_sports-board-strapi:
    external: true